syntax = 'proto3';package route;service Route {  rpc createRoute(CreateRouteInput) returns (CreateRouteOutput);  rpc updateRoute(UpdateRouteInput) returns (UpdateRouteOutput);}message CreateRouteInput {  string routeName = 1;}message CreateRouteOutput {  string id = 1;  string routeName = 2;  string userId = 3;}message UpdateRouteInput {  string id = 1;  string routeName = 2;  string userId = 3;}message UpdateRouteOutput {  string id = 1;  string routeName = 2;  string userId = 3;}