syntax = 'proto3';import 'google/protobuf/wrappers.proto';package achievement;service Achievements {  rpc  getAchievements(AchievementInput) returns (getAchievementsMany);  rpc  getAchievement(getAchievementByIdInput) returns (AchievementOutput);  rpc  createAchievement(createAchievementInput) returns (AchievementOutput);  rpc deleteAchievement(deleteAchievementInput) returns (google.protobuf.BoolValue);}message AchievementInput {}message AchievementOutput {  string id = 1;  string name = 2;  int32 points = 3;}message getAchievementsMany {  repeated AchievementOutput achievements = 1;}message getAchievementByIdInput {  string id = 1;}message createAchievementInput {  string name = 1;  int32 points = 2;}message deleteAchievementInput {  string id = 1;}