syntax = 'proto3';

package quest;

service Quest {
  rpc createQuest(CreateQuest) returns (QuestEntity);
  rpc updateQuest(UpdateQuest) returns (QuestEntity);
  rpc findMany(FindManyQuests) returns (FindManyQuestsResult);
  rpc findOne(FindOneQuest) returns(QuestEntity);
  rpc deleteOne(DeleteOneQuest) returns (DeleteOneQuestResult);
  rpc deleteMany(DeleteManyQuests) returns(DeletedManyQuestsResult);
  rpc attachQuestToUser(AttacheQuestToUser) returns(UserQuestEntity);
  rpc completeQuest(CompleteQuest) returns(UserQuestEntity);
  rpc deleteQuests(DeleteUserQuestInput) returns(DeleteUserQuests);
  rpc updateQuests(UpdateUserQuest) returns(UserQuestEntity);
  rpc findManyUserQuests(FindManyUserQuests) returns(FindManyUserQuestsOutput);
  rpc findOneUserQuest(FindOneUserQuest) returns(UserQuestEntity);
  rpc findAllUserQuests(FindAllUserQuests) returns(FindManyUserQuestsOutput);
}

enum QUEST_TYPE {
  UNSPECIFIED = 0;
  DEFAULT = 1;
  DAILY = 2;
  WEEKLY = 3;
}

enum QUEST_CONDITION {
  NO = 0;
  CREATE = 1;
  UPDATE = 2;
}

enum QUEST_FIELD {
  NO_FIELD = 0;
  STEPS = 1;
  POINTS = 2;
  ROUTES = 3;
  AWARDS = 4;
  EVENTS = 5;
  USERS = 6;
  CURRENT_COUNTRY = 7;
  DURATION = 8;
}

enum QUEST_STATUS {
  EMPTY = 0;
  IN_PROGRESS = 1;
  FINISHED = 2;
}
message UserQuestEntity {
  string id = 1;
  string userId = 2;
  string questId = 3;
  QUEST_STATUS status = 4;
  QUEST_CONDITION questCondition = 5;
  QUEST_FIELD questField = 6;
  QUEST_TYPE questType = 7;
  int32 progress = 8;
  int32 finishResult = 9;
  optional string completedAt = 10;
  string createdAt = 11;
}

message FindManyUserQuestsOutput {
  repeated UserQuestEntity userQuests = 1;
}

message FindAllUserQuests {
  optional string userId = 1;
}

message DeleteUserQuests {
  string id = 1;
}

message DeleteUserQuestInput {
  string questId = 1;
}

message AttacheQuestToUser {
  string userId = 1;
  string questId = 2;
}

message CompleteQuest {
  string userId = 1;
  string questId = 2;
}

message UpdateUserQuestData {
  optional int32 progress = 1;
  optional string status = 2;
  optional int32 finishResult = 3;
  optional string completedAt = 4;
}

message UpdateUserQuest {
  string userId = 1;
  UpdateUserQuestData data = 2;
}

message FindManyUserQuestsData  {
  optional string questId = 1;
  optional QUEST_STATUS status = 2;
  optional string createdAt = 3;
  optional string completedAt = 4;

}

message FindManyUserQuests {
    string userId = 1;
    FindManyUserQuestsData data = 2;
}

message FindOneUserQuest {
  string userId = 1;
  string questId = 2;
}

message QuestEntity {
  string id = 1;
  string questName = 2;
  string questDescription = 3;
  string questReward = 4;
  QUEST_CONDITION questCondition = 5;
  QUEST_TYPE questType = 6;
  string questCountry = 7;
  int32 questFinishResults = 8;
  QUEST_FIELD questField = 9;
}

message CreateQuest {
  string questName = 1;
  string questDescription = 2;
  string questReward = 3;
  QUEST_CONDITION questCondition = 4;
  QUEST_TYPE questType = 5;
  string questCountry = 6;
  int32 questFinishResults = 7;
  QUEST_FIELD questField = 8;
}

message UpdateQuest {
  string id = 1;
  optional string questName = 2;
  optional string questDescription = 3;
  optional string questReward = 4;
  optional QUEST_CONDITION questCondition = 5;
  optional QUEST_TYPE questType = 6;
  optional QUEST_FIELD questField = 7;
  optional string questCountry = 8;
  optional int32 questFinishResults = 9;
}

message FindManyQuests {
  optional QUEST_TYPE questType = 1;
  optional string questCountry = 2;
}

message FindManyQuestsResult {
  repeated QuestEntity quests = 1;
}

message FindOneQuest {
  string id = 1;
}

message DeleteOneQuest {
  string id = 1;
}

message DeleteOneQuestResult {
  string id = 1;
}

message DeleteManyQuests {
  repeated string id = 1;
}
message DeletedManyQuestsResult {
  repeated string id = 1;
}
