export enum KafkaTopicsEnum {
  USER_TELEMETRY_UPDATE = 'USER_TELEMETRY_UPDATE',
  USER_QUEST_PROGRESS = 'USER_QUEST_PROGRESS',
  USER_QUEST_STEPS_PROGRESS = 'USER_QUEST_STEPS_PROGRESS',
  USER_QUEST_AWARDS_PROGRESS = 'USER_QUEST_AWARDS_PROGRESS',
  USER_QUEST_POINTS_PROGRESS = 'USER_QUEST_POINTS_PROGRESS',
  USER_QUEST_ROUTES_PROGRESS = 'USER_QUEST_ROUTES_PROGRESS',
  USER_QUEST_EVENTS_PROGRESS = 'USER_QUEST_EVENTS_PROGRESS',
  USER_QUEST_DURATION_PROGRESS = 'USER_QUEST_DURATION_PROGRES',
  USER_QUEST_SOCKET_UPDATE = 'USER_QUEST_SOCKET_UPDATE',
}
