syntax = 'proto3';package weather;import "google/protobuf/empty.proto";import "google/protobuf/wrappers.proto";service Weather {  rpc weather(WeatherInput) returns (WeatherOutput);  rpc create(WeatherCreateInput) returns (google.protobuf.Empty);  rpc updateOne(WeatherUpdateOneInput) returns (WeatherUpdateOneOutput);  rpc deleteOne(WeatherDeleteOneInput) returns (google.protobuf.BoolValue);}message WeatherInput {  string accountId = 1;  string userId = 2;  string country = 3;}message WeatherOutput {}message WeatherCreateInput { string accountId = 1; optional string country = 2; optional string city = 3;}message WeatherUpdateOneInput {  string weatherId = 1;  optional string country = 2;  optional string city = 3;  optional string accountId = 4;}message WeatherUpdateOneOutput {  string id = 1;  string accountId = 2;  optional string city = 3;  optional string country = 4;}message WeatherDeleteOneInput {  string weatherId = 1;}